FROM bitnami/spark:4.0

USER root
RUN install_packages curl
USER 1001
RUN curl https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.4.1/hadoop-aws-3.4.1.jar --output /opt/bitnami/spark/jars/hadoop-aws-3.4.1.jar 
RUN curl https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-core/1.12.720/aws-java-sdk-core-1.12.720.jar --output /opt/bitnami/spark/jars/aws-java-sdk-core-1.12.720.jar 
RUN curl https://repo1.maven.org/maven2/software/amazon/awssdk/aws-core/2.32.21/aws-core-2.32.21.jar --output /opt/bitnami/spark/jars/aws-core-2.32.21.jar 
